baseURL = "https://hljdxjiang.github.io/"
languageCode = "zh-cn"
title = "springboot学习笔记"
theme = "hugo-PaperMod"

[params]
  env = "production"
  description = "springboot学习笔记"
  author = "milaozhi"

  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  [params.profileMode]
    enabled = true
    title = "milaozhi"
    subtitle = "一个失业的码农、技术经理。写点东西记录学习的点滴。"
    imageUrl = "/avatar.png"  # 放 public/avatar.png
    imageTitle = "头像"

    [[params.profileMode.buttons]]
      name = "文章"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "关于"
      url = "about"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/hljdxjiang"

#   [[params.socialIcons]]
#     name = "twitter"
#     url = "https://twitter.com/你的推特"

# 菜单
[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 4